// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/user_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/user_service.go -destination=internal/tests/mock/services/user_service_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	dto "fdlp-standard-api/internal/dto"
	models "fdlp-standard-api/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserService) CreateUser(user dto.CreateUserRequestBody) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceMockRecorder) CreateUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserService)(nil).CreateUser), user)
}

// CreateUserWithRole mocks base method.
func (m *MockUserService) CreateUserWithRole(userWithRole dto.CreateUserWithRoleRequestBody) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserWithRole", userWithRole)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserWithRole indicates an expected call of CreateUserWithRole.
func (mr *MockUserServiceMockRecorder) CreateUserWithRole(userWithRole any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserWithRole", reflect.TypeOf((*MockUserService)(nil).CreateUserWithRole), userWithRole)
}

// GetUser mocks base method.
func (m *MockUserService) GetUser(id string) (*dto.UserGetByIdResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", id)
	ret0, _ := ret[0].(*dto.UserGetByIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserServiceMockRecorder) GetUser(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserService)(nil).GetUser), id)
}

// GetUsersWithPagination mocks base method.
func (m *MockUserService) GetUsersWithPagination(filter map[string]any, page, pageSize int) ([]models.User, int64, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersWithPagination", filter, page, pageSize)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetUsersWithPagination indicates an expected call of GetUsersWithPagination.
func (mr *MockUserServiceMockRecorder) GetUsersWithPagination(filter, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersWithPagination", reflect.TypeOf((*MockUserService)(nil).GetUsersWithPagination), filter, page, pageSize)
}

// LoginUser mocks base method.
func (m *MockUserService) LoginUser(loginInfo dto.LoginUserRequestBody) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", loginInfo)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockUserServiceMockRecorder) LoginUser(loginInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockUserService)(nil).LoginUser), loginInfo)
}
