// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/websocket_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/websocket_service.go -destination=internal/tests/mock/services/websocket_service_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	reflect "reflect"

	websocket "github.com/gorilla/websocket"
	gomock "go.uber.org/mock/gomock"
)

// MockWebSocketService is a mock of WebSocketService interface.
type MockWebSocketService struct {
	ctrl     *gomock.Controller
	recorder *MockWebSocketServiceMockRecorder
	isgomock struct{}
}

// MockWebSocketServiceMockRecorder is the mock recorder for MockWebSocketService.
type MockWebSocketServiceMockRecorder struct {
	mock *MockWebSocketService
}

// NewMockWebSocketService creates a new mock instance.
func NewMockWebSocketService(ctrl *gomock.Controller) *MockWebSocketService {
	mock := &MockWebSocketService{ctrl: ctrl}
	mock.recorder = &MockWebSocketServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebSocketService) EXPECT() *MockWebSocketServiceMockRecorder {
	return m.recorder
}

// BroadcastMessage mocks base method.
func (m *MockWebSocketService) BroadcastMessage(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastMessage", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// BroadcastMessage indicates an expected call of BroadcastMessage.
func (mr *MockWebSocketServiceMockRecorder) BroadcastMessage(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastMessage", reflect.TypeOf((*MockWebSocketService)(nil).BroadcastMessage), message)
}

// RegisterClient mocks base method.
func (m *MockWebSocketService) RegisterClient(conn *websocket.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterClient", conn)
}

// RegisterClient indicates an expected call of RegisterClient.
func (mr *MockWebSocketServiceMockRecorder) RegisterClient(conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterClient", reflect.TypeOf((*MockWebSocketService)(nil).RegisterClient), conn)
}

// UnregisterClient mocks base method.
func (m *MockWebSocketService) UnregisterClient(conn *websocket.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnregisterClient", conn)
}

// UnregisterClient indicates an expected call of UnregisterClient.
func (mr *MockWebSocketServiceMockRecorder) UnregisterClient(conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterClient", reflect.TypeOf((*MockWebSocketService)(nil).UnregisterClient), conn)
}
